### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by ejangi** [muenzpraeger/salesforce-google-bigquery#3]
Hi René,

Thanks so much for the example code and the article on the [Salesforce developer blog](https://developer.salesforce.com/blogs/2018/08/integrate-google-bigquery-with-salesforce.html). It's been very helpful.

I'm currently messing with a project using some of this code to get up and running quickly. But, before I go much further I thought I'd check to see whether I can use this code or whether I need to rewrite my own.

Let me know what suits you.

Thanks,
James.

**Comment by muenzpraeger** [comment]
@ejangi Great to hear that my code is helpful! Feel free to use whatever you want. That's why it's open source. ;-)
