### ISSUE TITLE
Could you add a license?

### ISSUE THREAD

**Issue by ralphcallaway** [muenzpraeger/salesforce-google-bigquery#4]
Based on your dev article, https://developer.salesforce.com/blogs/2018/08/integrate-google-bigquery-with-salesforce, i'm guessing the intention is for this to be open source. But without a license this isn't something that can be used (ref https://opensource.stackexchange.com/a/1721). If your intention is for this to be re-usable would you mind adding a license to this project to that effect?

**Comment by fishygeek91** [comment]
This would be awesome. Thanks @muenzpraeger!

**Comment by muenzpraeger** [comment]
@ralphcallaway Thanks for pointing that out, sorry for the oversight on my end. Added a license.

Please note that I haven't touched anything on this repo since a few years. So I can't comment if it's still working. ; -)

**Comment by fishygeek91** [comment]
Thanks @muenzpraeger!! It works, just needs some unit tests and a lil love. I appreciate you getting to this so quickly!
